version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://user:password@postgres:5432/rbe_db
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rbe_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
